### ISSUE TITLE
ERROR in ./webpack/dev_helpers/CordovaDeviceRouter.js Module not found: Error: Can't resolve 'device.js'

### ISSUE THREAD

**Issue by enzym** [lakexyde/cordova-onsenui-vue-webpack-template#4]
For this Error:
ERROR in ./webpack/dev_helpers/CordovaDeviceRouter.js Module not found: Error: Can't resolve 'device.js' in '/.../webpack/dev_helpers' @ ./webpack/dev_helpers/CordovaDeviceRouter.js 1:17-37 @ multi ./src/main.js ./webpack/dev_helpers/CordovaDeviceRouter.js

Solution:
[https://github.com/centrual/cordova-template-framework7-vue-webpack/issues/71#issuecomment-34595359](url)

**Comment by rassemdev** [comment]
@enzym  page not found. can you re-check your url!

**Comment by enzym** [comment]
For some reason the comment in the linked issue may changed.
https://github.com/caiobiodere/cordova-template-framework7-vue-webpack/issues/71

yelban got the working solution.

**Comment by rassemdev** [comment]
@enzym there is other errors too

ERROR in ./~/onsenui/js/onsenui.js
Module build failed: Error: Couldn't find preset "env" relative to directory "/var/www/html/Test3/node_modules/onsenui"
    at /var/www/html/Test3/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/var/www/html/Test3/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/var/www/html/Test3/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/var/www/html/Test3/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/var/www/html/Test3/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/var/www/html/Test3/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/var/www/html/Test3/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/var/www/html/Test3/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/var/www/html/Test3/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/var/www/html/Test3/node_modules/babel-loader/lib/index.js:163:20)
 @ ./~/vue-onsenui/dist/vue-onsenui.js 8:142-160 8:209-237
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.0.108:8081 webpack/hot/dev-server ./src/main.js ./webpack/dev_helpers/CordovaDeviceRouter.js

**Comment by rassemdev** [comment]
@enzym there is other errors too

`ERROR in ./~/onsenui/js/onsenui.js
Module build failed: Error: Couldn't find preset "env" relative to directory "/var/www/html/Test3/node_modules/onsenui"
    at /var/www/html/Test3/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/var/www/html/Test3/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/var/www/html/Test3/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/var/www/html/Test3/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/var/www/html/Test3/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/var/www/html/Test3/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/var/www/html/Test3/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/var/www/html/Test3/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/var/www/html/Test3/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/var/www/html/Test3/node_modules/babel-loader/lib/index.js:163:20)
 @ ./~/vue-onsenui/dist/vue-onsenui.js 8:142-160 8:209-237
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.0.108:8081 webpack/hot/dev-server ./src/main.js ./webpack/dev_helpers/CordovaDeviceRouter.js`

**Comment by enzym** [comment]
I did some other changes (which I didn't assume to have any dependency to that error).
For example i updated onsenui/vue to 
  "onsenui": "^2.8.3",
  "vue": "^2.5.13",
  "vue-onsenui": "^2.4.3",
  "vuex": "^2.5.0"

I'll send you my package.json via mail.
